# Generated by Django 4.0.4 on 2023-02-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('status', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='upload')),
                ('facebook', models.TextField(blank=True, max_length=500)),
                ('instagram', models.TextField(blank=True, max_length=500)),
                ('telegram', models.TextField(blank=True, max_length=500)),
                ('whatsapp', models.TextField(blank=True, max_length=500)),
                ('status', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
