# Generated by Django 4.0.4 on 2023-02-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='insta_link',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
