# Generated by Django 5.0 on 2026-01-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review_insta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
