# Generated by Django 5.0 on 2026-01-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gallery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='status',
        ),
    ]
